"use client";

import { Context } from "@/components/Clients";
import { redirect } from "next/navigation";
import Link from "next/link";
import React, { useContext, useState } from "react";
import { toast } from "react-hot-toast";

const page = () => {
  const { user, setUser } = useContext(Context);
const [email,setEmail]=useState("")
const [password,setPassword]=useState("")

  const loginHandler = async (e) => {
    e.preventDefault();
    try {
      const resp = await fetch("/api/auth/login", {
        method: "POST",
        body: JSON.stringify({email,password}),
        headers: {
          "Content-Type": "application/json",
        },
      });
      const data = await resp.json();
      
      if (!data.success) return toast.error(data.message)
        setUser(data.user);
        toast.success(data.message)
    
    } catch (error) {
      return toast.error(error)
    }
  };
  if (user._id) return redirect("/");
  return (
    <div className="login">
      <section>
        <form onSubmit={loginHandler}>
          <input
            onChange={(e)=>setEmail(e.target.value)}
            value={email}
            type="email"
            name="email"
            placeholder="Enter Your Email"
          />
          <input
            onChange={(e)=>setPassword(e.target.value)}
            value={password}
            type="password"
            name="password"
            placeholder="Enter Your Password"
          />

          <button type="submit">Login</button>
          <p>OR</p>
          <Link href={"/register"}>New Here</Link>
        </form>
      </section>
    </div>
  );
};

export const metadata = {
  title: "Login",
  description: "Generated by Next.js",
};

export default page;
